### ISSUE TITLE
relays or configs?

### ISSUE THREAD

**Issue by bigmike77k** [luccaPossamai/optical#22]
i dont want to sound rude but is there an eta on configs for SU or maybe a way to relay the optical sensors for this mod to be more effective wireless power source or long range redstone signal, thank you.

**Comment by luccaPossamai** [comment]
you're not sounding rude, don't worry. About the relay, if you mean that the beam should continue after passing through the sensor, that's exactly one of the new features, I think this isn't in the repository yet. For now, I'm focusing on developing all these new features before thinking about config files. That's probably one of the things I'll work on soon, just because there's many requests for more environment for modpack makers(configs is one of em). One of the features take care of this SU problem.
