### ISSUE TITLE
Beams passing through closed trapdoors

### ISSUE THREAD

**Issue by DaPuffer** [luccaPossamai/optical#9]
Pretty much the opposite of issue #8
![image](https://github.com/luccaPossamai/optical/assets/132820752/8b3e0258-deeb-4284-a324-da7f2a578b0f)

**Comment by Frosticle** [comment]
Most likely happens to doors as well

**Comment by DaPuffer** [comment]
![image](https://github.com/luccaPossamai/optical/assets/132820752/f6b6ecc2-c06e-4ded-98a7-eec865b6a2d4)

**Comment by DaPuffer** [comment]
![image](https://github.com/luccaPossamai/optical/assets/132820752/e72d7e53-8c8e-4ed3-8a5c-8c559cea34b9)
the lazor beam might be racist.

**Comment by DaPuffer** [comment]
![image](https://github.com/luccaPossamai/optical/assets/132820752/6f8514c6-38cc-48cf-b35b-b2782142aa0e)
![image](https://github.com/luccaPossamai/optical/assets/132820752/8855a62b-2b19-4fd6-820d-b33935997cf5)
it also does not pass through vertical slabs from quark. depression

**Comment by luccaPossamai** [comment]
The problem is that there are certain blocks that cannot be generalized in terms of whether or not the laser can pass through. Think about the trapdoors and normal doors, depending on the direction of the block and the state(open/closed) the beam might pass or be blocked. Unfortunately with this blocks the tag generalization it's not the right way to represent the sense of reality. If I handle this doors problem, I gotta handle with the all other ones I decide to not let beam pass(like fence gates and such). Fixing all the specific blocks states and gotta map theses conditions to the beam is a job that will give anyone a headache.

**Comment by luccaPossamai** [comment]
For these blocks like moss carpet and iron trapdoors, thats an easy fix. I think that the tags like minecraft:carpets and minecraft:trapdoors for some rease don't apply for these blocks.

**Comment by luccaPossamai** [comment]
For other mods, the easy way to see this compatibility thing is verify if the mod blocks have the tag create_optical:beam_can_pass_through, or adding them manually.
